[[redirects]]
from = "https://a-kort.netlify.app/*"
to = "https://www.a-kort.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://a-kort.netlify.app/*"
to = "http://www.a-kort.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.a-kort.com/*"
to = "http://a-kort.netlify.app/:splat"
status = 301
force = true
